- .github/workflows/push-to-another-repository.yml
- build.sh
> 🧪 test : CI/CD 자동화 테스트 9 (레포명 변경)

- src/components/comment-item-component.tsx
- src/components/free-item-component.tsx
댓글 아이템, 게시판 아이템 컴포 넌트 제작했습니다. 
게시판 아이템 댓글 한 줄로 제한하고 말줄임표 표시하는 기능 추가 예정
resolves #6
> 💄 style: 게시판/댓글 아이템 컴포넌트 제작

- src/app/components/sah/page.tsx
- src/components/ui/input.tsx
- src/components/ui/search-input.tsx
- src/components/ui/textarea.tsx
> 💄 style : 인풋 컴포넌트 제작

- src/app/mypage/bookmark/page.tsx
> 💄 style: 나의 북마크 페이지 레이아웃 수정용 커밋

- src/app/plan/dates/page.tsx
- src/app/plan/page.tsx
> 💄 style: 여행일정 지역 선택 페이지 제작

- src/app/mypage/page.tsx
> 💄 style: 마이페이지 레이아웃 구성

- src/app/components/njs/page.tsx
- src/app/feed/page.tsx
- src/app/home/layout.tsx
- src/app/home/page.tsx
- src/app/mypage/bookmark/[id]/page.tsx
- src/app/mypage/layout.tsx
- src/app/mypage/page.tsx
- src/app/page.tsx
- src/app/plan/dates/layout.tsx
- src/app/plan/dates/page.tsx
- src/app/plan/page.tsx
- src/app/review/new/layout.tsx
- src/components/Navbar.tsx
- src/components/ui/randomItem.tsx
- src/components/ui/viewItem.tsx
> ♻️ refactor: 전체페이지 레이아웃 재조정

- src/app/home/page.tsx
- src/components/ui/drawerItem.tsx
- [] 새로운 기능 추가
- [] 버그 수정
- [] 코드에 영향을 주지 않는 변경사항(오타 수정, 탭 사이즈 변경, 변수명 변경)
- [] 코드 리팩토링
- [] 주석 추가 및 수정
- [] 문서 수정
- [] 테스트 추가, 테스트 리팩토링
- [] 빌드 부분 혹은 패키지 매니저 수정
- [] 배포 관련
- [] 접근성 개선
- [] 파일 혹은 폴더명 수정
- [] 파일 혹은 폴더 삭제
resolves #50
> 💄 style: 홈 페이지 레이아웃 구성

- src/app/components/sah/page.tsx
- src/app/feed/page.tsx
- src/app/mypage/layout.tsx
- src/app/mypage/page.tsx
- src/app/mypage/profiledit/page.tsx
- src/app/plan/page.tsx
- src/components/ui/profileItem.tsx
- src/components/ui/profileItemedit.tsx
- src/components/ui/searchInput.tsx
> 💄 style: 마이페이지 레이아웃 제작

- src/app/mypage/bookmark/[id]/page.tsx
- src/app/mypage/bookmark/page.tsx
- src/app/mypage/review/depth1/page.tsx
- src/app/mypage/review/depth2/page.tsx
- src/app/mypage/review/page.tsx
- src/components/ui/reviewItem.tsx
> 💄 style: 마이페이지 북마크와 리뷰 초안

- src/app/auth/layout.tsx
- src/app/auth/login/page.tsx
- src/components/Footer.tsx
> ♻️ refactor: 로그인 페이지 리팩토링 

- src/app/mypage/edit/page.tsx
- src/components/ui/profileItem.tsx
- src/components/ui/profileItemedit.tsx
> ♻️ refactor: 마이페이지 리팩토링

- api/bruno/PROJECT-6pm/bruno.json
- api/bruno/PROJECT-6pm/collection.bru
- api/bruno/PROJECT-6pm/environments/6pm.bru
- api/bruno/PROJECT-6pm/여행계획 목록상세조회.bru
- api/bruno/PROJECT-6pm/여행계획 목록전체조회.bru
- api/bruno/PROJECT-6pm/여행후기 목록상세조회-일자별.bru
- api/bruno/PROJECT-6pm/여행후기 목록상세조회-장소별.bru
- api/bruno/PROJECT-6pm/여행후기 목록상세조회-전체.bru
- api/bruno/PROJECT-6pm/여행후기 목록조회-일자별.bru
- api/bruno/PROJECT-6pm/여행후기 목록조회-장소별.bru
- api/bruno/PROJECT-6pm/여행후기 목록조회-전체.bru
- api/bruno/PROJECT-6pm/회원정보조회.bru
- api/dbinit/team/data.js
- eslint.config.mjs
> 🐳 chore: 데이터구조 설정

- api/dbinit/team/data.js
> 🐳 chore: data.js 업데이트

- src/app/components/chj/getpost/page.tsx
>  🐳 chore: 브루노 연동 테스트

- src/app/home/page.tsx
- src/components/feature/serverLocation.tsx
- src/lib/api/utils/getTodayString.ts
- src/lib/api/utils/getTodayYYYYMMDD.ts
- src/lib/api/weather.ts
- [] 커밋 메시지 컨벤션에 맞게 작성했습니다.
- [] 변경 사항에 대한 테스트를 했습니다.(버그 수정/기능에 대한 테스트).
resolves #106
> ✨ feat: 위치·날짜 표시, 날씨 API 연동

- src/components/feature/viewItem.tsx
> 💄 style: swiper pagination 스타일 변경

- src/app/plan/TravelPage.tsx
- src/app/plan/dates/layout.tsx
- src/app/plan/dates/page.tsx
- src/app/plan/edit/layout.tsx
- src/app/plan/search/layout.tsx
- src/app/plan/view/layout.tsx
- src/components/feature/backButton.tsx
- src/components/feature/planCalendar.tsx
> ✨ feat: 캘린더 추가, 세션 스토리지 연동

- src/app/components/njs/page.tsx
- src/components/feature/locationWeatherBox.tsx
- src/components/feature/searchRegion.tsx
- src/components/feature/serverLocation.tsx
- src/components/form/loginForm.tsx
- src/data/functions/weather.ts
- useSearchParams 관련 : NEXT13 이상에서 <Suspense> 감싸지 않음에 따른 오류 => 임시 주석처리, 이후 redirect 관련 확인 필요
resolves #163
> 🐛 bug: 배포 관련 오류 처리

- src/app/feed/page.tsx
- src/components/feature/viewItem.tsx
- src/data/functions/plan.ts
> ✨ feat: 피드페이지 후기 조회

- next.config.ts
- src/components/feature/locationWeatherBox.tsx
- src/components/feature/serverLocation.tsx
- src/data/functions/weather.ts
- src/lib/api/weather.ts
> 🐛 bug: 날씨API - Client 로 재조정 

- src/app/plan/edit/preview/page.tsx
- src/app/plan/edit/schedule/page.tsx
- src/app/plan/success/page.tsx
- src/app/plan/view/page.tsx
- src/components/feature/searchNav.tsx
- src/components/form/plan/planDetailForm.tsx
- src/components/form/plan/planRegion.tsx
- src/components/form/plan/planReplyForm.tsx
- src/components/form/searchInput.tsx
- src/components/plan/searchAll.tsx
- src/components/ui/planListItem.tsx
- src/components/ui/removeTag.tsx
- src/data/actions/plan.ts
- src/hook/useSearchHandler.ts
- src/types/plan.ts
- src/zustand/planStore.ts
> ✨ feat: 일차별 계획(댓글) 등록 제작

- src/app/plan/edit/preview/page.tsx
- src/components/feature/fillScheduleCard.tsx
- src/components/plan/categorySelect.tsx
- src/components/plan/previewContent.tsx
- src/components/plan/searchAll.tsx
- src/components/ui/dayScheduleCard.tsx
- src/components/ui/planListItem.tsx
- src/hook/useContentDetail.ts
- src/hook/usePlanSchedule.ts
- src/hook/useSearchHandler.ts
- src/hook/useSearchReset.ts
- src/hook/useTravelData.ts
- src/types/plan.ts
> ✨ feat: 날짜 변경 시 검색 상태 초기화 기능 추가

- src/components/feature/feedDetailContent.tsx
- src/components/feature/locationModal.tsx
- src/components/feature/selectWriteReview.tsx
- src/components/feature/viewItem.tsx
- src/components/form/reviewDetailForm.tsx
- src/components/form/reviewFormAll.tsx
- src/components/form/reviewSelect.tsx
- src/data/actions/review.ts
- src/types/review.ts
- 모달창 출력을 위한 data-contentid 추가 설정
- 기본 데이터 content: extra 에서 location이 string[] 이 아닌 object[] 임을 확인 => 수정
resolves #203
> ♻️ refactor: 장소관련 data-contentid 추가연결 

- src/components/feature/commentDeleteForm.tsx
- src/components/feature/commentEditForm.tsx
- src/components/feature/feedContent.tsx
- src/components/feature/feedDetailContent.tsx
- src/components/ui/commentItem.tsx
- src/data/actions/reply.ts
> ✨ feat: 여행리뷰관련 댓글 수정 및 삭제

- src/app/plan/success/page.tsx
- src/components/feature/selectMypage.tsx
- src/components/form/plan/planDetailForm.tsx
- src/components/form/searchInput.tsx
- src/components/plan/planDetailContent.tsx
- src/components/plan/searchAll.tsx
- src/components/plan/searchResult.tsx
- src/components/plan/searchSection.tsx
- src/components/ui/randomItem.tsx
- src/data/functions/travel.ts
> ✨ feat: 여행계획 성공페이지에 홈버튼 추가

- src/components/feature/feedDetailContent.tsx
- src/components/ui/commentItem.tsx
> 🐛 bug: 댓글 프로필 사진 출력되지 않는 오류 해결

- src/app/(auth)/login/page.tsx
- src/app/mypage/edit/page.tsx
- src/app/mypage/page.tsx
- src/components/feature/myPassword.tsx
- src/components/feature/selectMypage.tsx
- src/components/form/profileItemEdit.tsx
- src/components/form/singUpForm.tsx
- src/components/ui/profileItem.tsx
- src/data/actions/user.ts
- src/data/functions/user.ts
- src/types/user.ts
- src/zustand/userStore.ts
> ✨ feat: 마이페이지 편집 

- package-lock.json
- package.json
- src/app/plan/test/page.tsx
- src/components/feature/fillScheduleCard.tsx
- src/components/plan/naverMap.tsx
> 🧪 test: 여행계획 페이지에 네이버지도 연동

- src/components/feature/feedContent.tsx
- src/components/feature/feedDetailContent.tsx
- src/components/feature/selectBookmark.tsx
- src/components/feature/toggleComponents.tsx
- src/data/functions/bookmark.ts
> ✨ feat: 북마크 기능 점검 및 마이페이지 추가 임시커밋

- src/components/feature/homePlanItem.tsx
- src/components/form/imageUploader.tsx
- src/components/form/profileItemEdit.tsx
- src/components/form/singUpForm.tsx
- src/data/actions/user.ts
> ♻️ refactor: 회원업데이트 함수 폼액션 변경

- api/dbinit/team/data.json
> 🐳 chore: DB데이터 수정

- api/dbinit/team/data.json
> 🐳 chore: DB데이터 추가수정

- api/dbinit/team/data.json
> 🐛 bug: 파일경로 카멜케이스 준수

- api/dbinit/team/data.json
- src/components/feature/feedContent.tsx
- src/components/feature/feedDetailContent.tsx
- src/components/feature/viewItem.tsx
- src/components/feature/viewItemSkeleton.tsx
- src/components/form/profileItemEdit.tsx
- src/components/ui/commentItem.tsx
- src/components/ui/commentitemSkeleton.tsx
- src/components/ui/profileItem.tsx
- src/components/ui/randomItem.tsx
- src/components/ui/randomItemSkeleton.tsx
> 🐳 chore: DB데이터 구조조정

- src/app/review/(write)/new/ReviewPage.tsx
- src/components/feature/dropdownItem.tsx
- src/components/feed/feedContent.tsx
> ✨ feat: 필터링(최신순, 오래된순) 구현

- api/dbinit/team/data.json
- src/components/feed/feedContent.tsx
- src/components/form/plan/planDetailForm.tsx
- src/components/plan/searchAll.tsx
> 🐳 chore: db데이터 contentID 재설정

- src/components/plan/dayScheduleCard.tsx
- src/components/plan/fillScheduleCard.tsx
- src/components/plan/naverMap.tsx
- src/components/plan/planDetailContent.tsx
- src/components/plan/scheduleContent.tsx
> ✨ feat: 네이버지도에 여행장소 연동

- src/app/(auth)/login/page.tsx
- src/components/Footer.tsx
- src/components/feature/locationModal.tsx
- src/components/form/mypage/profileItemEdit.tsx
- src/components/home/drawerItem.tsx
- src/components/home/homePlanItem.tsx
- src/components/home/randomItem.tsx
- src/components/ui/btn.tsx
- src/data/actions/bookmark.ts
- src/types/bookmark.ts
- src/types/user.ts
> ✨ feat: 장소 북마크 기능 추가

- src/components/plan/modifyScheduleContent.tsx
- src/components/plan/previewContent.tsx
> 🐛 bug: daylist 타입에러 수정

- src/components/photoweb/koreaMap.tsx
> ♻️ refactor: 지도 URL 코드 수정

- src/app/feed/[id]/edit/page.tsx
- src/app/mypage/(view)/layout.tsx
- src/app/mypage/(view)/page.tsx
- src/app/photomap/layout.tsx
- src/app/plan/edit/preview/page.tsx
- src/app/plan/layout.tsx
- src/app/plan/page.tsx
- src/app/review/(write)/new/layout.tsx
- src/components/feature/locationModal.tsx
- src/components/feature/loginStatusConfirm.tsx
- src/components/feed/commentEditForm.tsx
- src/components/feed/commentForm.tsx
- src/components/form/auth/loginForm.tsx
- src/components/form/mypage/bookAndReview.tsx
- src/components/form/mypage/profileItemEdit.tsx
- src/components/home/drawerItem.tsx
- src/components/home/randomItem.tsx
- src/data/actions/user.ts
- src/types/user.ts
- src/zustand/userStore.ts
> ✨ feat: 사용자 인증 토큰 갱신 기능 추가

- src/app/layout.tsx
- src/app/not-found.tsx
- src/components/ClientLayout.tsx
> ♻️ refactor: 레이아웃, 404페이지 컴포넌트 분리

- src/components/feature/locationModal.tsx
- src/components/feature/viewItem.tsx
- src/components/form/review/reviewSelect.tsx
- src/components/home/drawerItem.tsx
- src/components/home/randomItem.tsx
- src/components/mypage/bookmarkContent.tsx
- src/components/mypage/placeItem.tsx
- src/components/mypage/selectBookmark.tsx
- src/components/mypage/selectMypage.tsx
- src/components/ui/dayItem.tsx
- src/data/actions/bookmark.ts
- src/types/bookmark.ts
- src/types/review.ts
> ✨ feat: 북마크 기능 내 콘텐츠 타입 추가

- src/components/plan/dayScheduleCard.tsx
- src/components/plan/fillScheduleCard.tsx
- src/components/plan/modifyScheduleContent.tsx
- src/components/plan/planDetailContent.tsx
- src/components/plan/planListItem.tsx
> ✨ feat: 여행일정 장소 삭제 기능 구현

- src/components/mypage/selectMypage.tsx
> ♻️ refactor: 마이페이지 여행 일정 정렬 코드 추가

- src/components/form/mypage/bookAndReview.tsx
- src/components/form/review/reviewSelect.tsx
- src/components/mypage/bookmarkContent.tsx
- src/components/mypage/bookmarkItem.tsx
- src/components/mypage/selectReviewTab.tsx
- src/components/review/selectWriteReview.tsx
> Refator/qa allpages/psy

- src/app/review/(write)/new/ReviewPage.tsx
- src/components/feature/reviewdropdownItem.tsx
- src/components/mypage/selectBookmark.tsx
> ♻️ refactor: 북마크와 기록페이지 필터링 변경

- src/app/intro/page.tsx
- src/app/not-found.tsx
- src/app/plan/[id]/layout.tsx
- src/app/plan/[id]/page.tsx
- src/components/ClientLayout.tsx
- src/components/plan/planDetailContent.tsx
- src/components/plan/planDetailContentSkeleton.tsx
- src/components/plan/scheduleContent.tsx
> 💄 style: 인덱스페이지 스타일링 조정

- src/app/intro/page.tsx
> 🐛 bug: 인트로 페이지 깃허브 링크 수정

- src/components/review/successLink.tsx
- src/data/actions/review.ts
> 🐛 bug: 글 작성 이후 planId연동
